"""
Tier-3 backend: emit a Blender-Python script that drives the built-in Ocean
modifier with the exact same parameters used by Tiers 1 and 2.

We do *not* import bpy here -- the user runs the emitted script with:

    blender --background --python <out_mp4>.blend.py

The script:
  - sets up a Cycles scene (CUDA/OptiX),
  - adds a plane with an Ocean modifier (Mastin-Watterberg-Mareda spectrum +
    Tessendorf choppiness + foam),
  - sets sun position from azimuth/elevation,
  - configures camera height/pitch/yaw/FOV,
  - animates `time` to the requested duration,
  - renders to the requested mp4.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Tuple
import textwrap

if TYPE_CHECKING:
    from . import WindSpec, WaterSpec, Sun, Sky, Camera


_TEMPLATE = '''\
"""Generated by HNA.modules.wave_synth.render_blender — do not edit by hand."""
import bpy
import math
from mathutils import Vector

# ---- scene reset --------------------------------------------------------
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.render.engine = 'CYCLES'
try:
    scene.cycles.device = 'GPU'
except Exception:
    pass
scene.render.fps = {fps_int}
scene.frame_start = 1
scene.frame_end = {n_frames}
scene.render.resolution_x = {res_x}
scene.render.resolution_y = {res_y}
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = 'MPEG4'
scene.render.ffmpeg.codec = 'H264'
scene.render.ffmpeg.constant_rate_factor = 'MEDIUM'
scene.render.filepath = r"{out_mp4}"
scene.cycles.samples = 64

# ---- ocean plane --------------------------------------------------------
bpy.ops.mesh.primitive_plane_add(size={ocean_size_m}, location=(0, 0, 0))
plane = bpy.context.object
plane.name = "OceanSurface"
mod = plane.modifiers.new(name="Ocean", type='OCEAN')
mod.spatial_size   = {patch_L_m}
mod.resolution     = {ocean_resolution_steps}    # 2**n; corresponds to grid of 2**n * 16
mod.depth          = {depth_m}
mod.wind_velocity  = {U10:.4f}
mod.wave_alignment = 1.0
mod.wave_direction = {wind_direction_factor:.4f}    # in [-1,1]; sign flips align direction
mod.choppiness     = {choppiness:.4f}
mod.foam_coverage  = {foam_coverage:.4f}
mod.use_foam       = True
mod.use_normals    = True
mod.random_seed    = {seed}

# Animate ocean time across the clip
mod.time = 0.0
mod.keyframe_insert(data_path="time", frame=1)
mod.time = float({duration_s})
mod.keyframe_insert(data_path="time", frame={n_frames})
for f in plane.animation_data.action.fcurves:
    for kp in f.keyframe_points:
        kp.interpolation = 'LINEAR'

# ---- water material -----------------------------------------------------
mat = bpy.data.materials.new(name="Water")
mat.use_nodes = True
nt = mat.node_tree
for n in list(nt.nodes):
    nt.nodes.remove(n)
out = nt.nodes.new("ShaderNodeOutputMaterial");        out.location = ( 600, 0)
mix = nt.nodes.new("ShaderNodeMixShader");             mix.location = ( 380, 0)
glossy = nt.nodes.new("ShaderNodeBsdfGlossy");         glossy.location = (160, 120)
trans = nt.nodes.new("ShaderNodeBsdfTransparent");     trans.location = (160, -80)
fresnel = nt.nodes.new("ShaderNodeFresnel");           fresnel.location = ( 0, 60)
fresnel.inputs["IOR"].default_value = 1.33
glossy.inputs["Color"].default_value = ({wc_r}, {wc_g}, {wc_b}, 1.0)
glossy.inputs["Roughness"].default_value = 0.02
nt.links.new(fresnel.outputs[0], mix.inputs[0])
nt.links.new(trans.outputs[0],  mix.inputs[1])
nt.links.new(glossy.outputs[0], mix.inputs[2])
nt.links.new(mix.outputs[0],    out.inputs[0])
plane.data.materials.append(mat)

# ---- foam material via Ocean's foam attribute ---------------------------
# (left as a separate vertex-color-driven node group — omitted for brevity)

# ---- world / sky --------------------------------------------------------
world = bpy.data.worlds.new("World"); scene.world = world
world.use_nodes = True
wn = world.node_tree
for n in list(wn.nodes): wn.nodes.remove(n)
wout = wn.nodes.new("ShaderNodeOutputWorld");    wout.location = (400, 0)
sky = wn.nodes.new("ShaderNodeTexSky");          sky.location = (200, 0)
sky.sky_type = 'NISHITA'
sky.turbidity = {turbidity:.3f}
sky.sun_elevation = math.radians({sun_elevation_deg:.4f})
sky.sun_rotation  = math.radians({sun_azimuth_deg:.4f})
sky.air_density = 1.0
bg = wn.nodes.new("ShaderNodeBackground");       bg.location = (0, 0)
bg.inputs["Strength"].default_value = {sun_intensity:.4f}
wn.links.new(sky.outputs[0], bg.inputs[0])
wn.links.new(bg.outputs[0],  wout.inputs[0])

# ---- sun lamp -----------------------------------------------------------
bpy.ops.object.light_add(type='SUN', location=(0, 0, 50))
sun_obj = bpy.context.object
sun_obj.data.energy = 4.0 * {sun_intensity:.4f}
sun_obj.data.color = ({sun_r}, {sun_g}, {sun_b})
saz = math.radians({sun_azimuth_deg:.4f})
sel = math.radians({sun_elevation_deg:.4f})
sun_obj.rotation_euler = (math.pi/2 - sel, 0.0, -saz)

# ---- camera -------------------------------------------------------------
bpy.ops.object.camera_add(location=(0, 0, {cam_height_m:.4f}))
cam = bpy.context.object
scene.camera = cam
cam.data.lens_unit = 'FOV'
cam.data.angle = math.radians({cam_fov_deg:.4f})
cam.rotation_euler = (math.radians(90.0 + ({cam_pitch_deg:.4f})),
                      0.0,
                      math.radians(-({cam_yaw_deg:.4f})))
{dof_block}

# ---- render -------------------------------------------------------------
bpy.ops.render.render(animation=True)
'''


def build_script(*, out_mp4: str, duration_s: float, fps: float,
                 resolution: Tuple[int, int],
                 wind: "WindSpec", water: "WaterSpec",
                 sun: "Sun", sky: "Sky",
                 camera: "Camera",
                 seed: int, patch_L_m: float, grid_N: int) -> str:
    """Build the .py script string. Caller writes it next to the mp4."""
    n_frames = int(round(duration_s * fps))
    # Map our N (256, 512, ...) onto Blender's "resolution" exponent: Blender
    # uses 2**n with resolution = log2(N/16) approximately -> we just clip 7..9.
    import math
    blender_steps = int(max(5, min(9, round(math.log2(max(grid_N, 32) / 16)))))
    # Wind direction maps to wave_direction in [-1, +1].
    # Blender's wave_direction is along the local X axis when 1; we normalize to a single scalar.
    import numpy as np
    wd = np.cos(np.deg2rad(wind.direction_deg))   # crude single-axis projection
    wd = float(np.clip(wd, -1.0, 1.0))

    if (camera.aperture_fstop is not None
            and camera.focal_mm is not None
            and camera.focus_distance_m is not None):
        dof = (
            f'cam.data.lens = {camera.focal_mm:.3f}\n'
            f'cam.data.dof.use_dof = True\n'
            f'cam.data.dof.aperture_fstop = {camera.aperture_fstop:.3f}\n'
            f'cam.data.dof.focus_distance = {camera.focus_distance_m:.3f}'
        )
    else:
        dof = '# (no depth of field requested)'

    out_path_escaped = str(out_mp4).replace("\\", "\\\\")

    return _TEMPLATE.format(
        out_mp4=out_path_escaped,
        n_frames=n_frames,
        fps_int=int(round(fps)),
        res_x=int(resolution[0]),
        res_y=int(resolution[1]),
        ocean_size_m=max(patch_L_m * 4, 1000.0),
        patch_L_m=float(patch_L_m),
        ocean_resolution_steps=blender_steps,
        depth_m=float(wind.depth_m),
        U10=float(wind.speed_U10),
        wind_direction_factor=wd,
        choppiness=float(water.choppiness),
        foam_coverage=float(water.foam_coverage),
        seed=int(seed),
        duration_s=float(duration_s),
        wc_r=float(water.water_color[0]),
        wc_g=float(water.water_color[1]),
        wc_b=float(water.water_color[2]),
        sun_r=float(sun.color[0]),
        sun_g=float(sun.color[1]),
        sun_b=float(sun.color[2]),
        sun_intensity=float(sun.intensity),
        turbidity=float(sky.turbidity),
        sun_elevation_deg=float(sun.elevation_deg),
        sun_azimuth_deg=float(sun.azimuth_deg),
        cam_height_m=float(camera.height_m),
        cam_pitch_deg=float(camera.pitch_deg),
        cam_yaw_deg=float(camera.yaw_deg),
        cam_fov_deg=float(camera.fov_deg),
        dof_block=textwrap.indent(dof, ""),
    )
